"""add tags to community

Revision ID: 2e4b94de7a79
Revises: 7b231fb97f7e
Create Date: 2024-11-01 10:49:29.673257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4b94de7a79'
down_revision: Union[str, None] = '7b231fb97f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.execute("UPDATE community SET tags = ARRAY[]::text[] WHERE tags IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'tags')
    # ### end Alembic commands ###
