"""add images to post

Revision ID: 98d590b26c8a
Revises: 726efb06162e
Create Date: 2024-05-22 23:59:59.008870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d590b26c8a'
down_revision: Union[str, None] = '726efb06162e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('post', 'images')
    # ### end Alembic commands ###
