"""empty message

Revision ID: c84feee029fa
Revises: 1002ef69bd1c
Create Date: 2024-09-18 22:22:41.698873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84feee029fa'
down_revision: Union[str, None] = '1002ef69bd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('banner_url', sa.String(length=1024), nullable=True))
    op.drop_column('community', 'cover_art_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('cover_art_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('community', 'banner_url')
    # ### end Alembic commands ###
